### ISSUE TITLE
Create a checkbox list with the Pin Functions

### ISSUE THREAD

**Issue by hildogjr** [xesscorp/PadPainter#1]
@devbisme, first of all, interesting tool. Really good to check BGAs and big designs.
Did you use some tool to first design the GUI or it was by handle? I was something like the `kicost` distributor list on GUI to use in the "Pin Functions", creating a two columns design and "less big horizontal design".
Also with the right click options "Select All", "Unselect All" and "Toggle" as in `kicost`.

**Comment by xesscorp** [comment]
@hildogjr, I just coded the GUI by hand with calls to wxpython. For simple GUIs, that seems the easiest way for me.

**Comment by hildogjr** [comment]
Understood. And yes, have to be simple as possible.
I will check this implementation, that for me appear to group better the controls and be more responsible to different monitor resolution (in my small one is using almost all the horizontal space). This will change 1 or 2 graphic controls.

**Comment by hildogjr** [comment]
Fixed with #2 .
